#!/bin/bash
# =============================================================================
# NanoClaw — Slack File Sharing Patch
# Generated by The Force 🌌
#
# Run this from the NanoClaw project root:
#   bash groups/slack_jedi-nano-claw/apply-slack-files-patch.sh
#
# What this does:
#   1. Patches src/channels/slack.ts to detect & download Slack file attachments
#   2. Files are saved to the group's IPC directory → visible to the agent at
#      /workspace/ipc/files/<filename> inside the container
#   3. File references are appended to the message text so the agent sees them
#
# Requirements:
#   - SLACK_BOT_TOKEN must be set in .env (already required for Slack to work)
#   - Your Slack bot needs the `files:read` scope
# =============================================================================

set -e

SLACK_TS="src/channels/slack.ts"

echo "📦 Backing up $SLACK_TS → ${SLACK_TS}.bak"
cp "$SLACK_TS" "${SLACK_TS}.bak"

echo "✏️  Patching $SLACK_TS ..."

# Use Node.js to apply the patch (avoids sed cross-platform issues)
node --input-type=module << 'EOF'
import fs from 'fs';

const filePath = 'src/channels/slack.ts';
let src = fs.readFileSync(filePath, 'utf-8');

// ── Patch 1: add fetch import at the top ────────────────────────────────────
if (!src.includes("import { resolveGroupIpcPath }")) {
  src = src.replace(
    `import { updateChatName } from '../db.js';`,
    `import { updateChatName } from '../db.js';
import { resolveGroupIpcPath } from '../group-folder.js';`
  );
  console.log('✅ Patch 1: Added resolveGroupIpcPath import');
} else {
  console.log('⏭️  Patch 1 already applied');
}

// ── Patch 2: add group folder to constructor opts ────────────────────────────
if (!src.includes('groupFolder: string')) {
  src = src.replace(
    `export interface SlackChannelOpts {
  onMessage: OnInboundMessage;
  onChatMetadata: OnChatMetadata;
  registeredGroups: () => Record<string, RegisteredGroup>;
}`,
    `export interface SlackChannelOpts {
  onMessage: OnInboundMessage;
  onChatMetadata: OnChatMetadata;
  registeredGroups: () => Record<string, RegisteredGroup>;
  groupFolder: string;
}`
  );
  console.log('✅ Patch 2: Added groupFolder to SlackChannelOpts');
} else {
  console.log('⏭️  Patch 2 already applied');
}

// ── Patch 3: allow messages with files but no text ───────────────────────────
if (src.includes('if (!msg.text) return;')) {
  src = src.replace(
    `      if (!msg.text) return;`,
    `      const hasFiles = !!(msg as Record<string, unknown>).files;
      if (!msg.text && !hasFiles) return;`
  );
  console.log('✅ Patch 3: Allow messages with files but no text');
} else {
  console.log('⏭️  Patch 3 already applied');
}

// ── Patch 4: download files and append to content ───────────────────────────
if (!src.includes('downloadSlackFiles')) {
  // Replace the content assignment block
  src = src.replace(
    `      let content = msg.text;
      if (this.botUserId && !isBotMessage) {`,
    `      let content = msg.text ?? '';
      // Download any attached files and save to IPC files dir
      if (!isBotMessage) {
        const rawFiles = (msg as Record<string, unknown>).files as Array<{
          id?: string;
          name?: string;
          mimetype?: string;
          url_private_download?: string;
        }> | undefined;
        if (rawFiles?.length) {
          content += await this.downloadSlackFiles(rawFiles, jid);
        }
      }
      if (this.botUserId && !isBotMessage) {`
  );
  console.log('✅ Patch 4: Added file download call in message handler');
} else {
  console.log('⏭️  Patch 4 already applied');
}

// ── Patch 5: add downloadSlackFiles method ──────────────────────────────────
if (!src.includes('private async downloadSlackFiles')) {
  src = src.replace(
    `  private async flushOutgoingQueue`,
    `  private async downloadSlackFiles(
    files: Array<{ id?: string; name?: string; mimetype?: string; url_private_download?: string }>,
    jid: string,
  ): Promise<string> {
    // Find the group folder for this JID so we can write to its IPC files dir
    const groups = this.opts.registeredGroups();
    const group = groups[jid];
    if (!group) return '';

    const groupIpcPath = resolveGroupIpcPath(group.folder);
    const filesDir = \`\${groupIpcPath}/files\`;
    fs.mkdirSync(filesDir, { recursive: true });

    let refs = '';
    for (const file of files) {
      if (!file.url_private_download || !file.name) continue;
      try {
        // Download using the bot token via Slack's web client
        const res = await fetch(file.url_private_download, {
          headers: { Authorization: \`Bearer \${this.app.client.token}\` },
        });
        if (!res.ok) {
          logger.warn({ file: file.name, status: res.status }, 'Failed to download Slack file');
          continue;
        }
        const buffer = Buffer.from(await res.arrayBuffer());
        // Sanitize filename
        const safeName = file.name.replace(/[^a-zA-Z0-9._-]/g, '_');
        const dest = \`\${filesDir}/\${safeName}\`;
        fs.writeFileSync(dest, buffer);
        // Agent sees this path as /workspace/ipc/files/<name>
        refs += \`\\n[SLACK FILE: /workspace/ipc/files/\${safeName} (\${file.mimetype ?? 'application/octet-stream'})]\`;
        logger.info({ file: file.name, dest, size: buffer.length }, 'Slack file downloaded');
      } catch (err) {
        logger.error({ file: file.name, err }, 'Error downloading Slack file');
      }
    }
    return refs;
  }

  private async flushOutgoingQueue`
  );
  console.log('✅ Patch 5: Added downloadSlackFiles method');
} else {
  console.log('⏭️  Patch 5 already applied');
}

// ── Patch 6: thread groupFolder into constructor call ───────────────────────
// In registry.ts the channel factory passes opts — update SlackChannel call
// Actually update the registerChannel call at the bottom of slack.ts
if (!src.includes('groupFolder: opts.registeredGroups')) {
  // We need to pass groupFolder through ChannelOpts — check if it's there
  // For now just pass a placeholder; full wiring needs registry update too
  console.log('ℹ️  Patch 6: groupFolder wiring requires registry.ts update (see note below)');
}

fs.writeFileSync(filePath, src);
console.log('');
console.log('✅ All patches applied to', filePath);
EOF

echo ""
echo "📝 NOTE: You also need to pass 'groupFolder' through ChannelOpts in src/channels/registry.ts"
echo "   Add 'groupFolder: string' to ChannelOpts interface and pass it when constructing SlackChannel."
echo ""
echo "🔨 Rebuilding..."
npm run build

echo ""
echo "🎉 Done! Restart NanoClaw and your Slack bot can now receive file attachments."
echo "   Files will appear in the agent as: [SLACK FILE: /workspace/ipc/files/<name> (mime/type)]"
echo ""
echo "🔑 Make sure your Slack bot has the 'files:read' scope in your Slack App settings."
